# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then call a random question with `pick()` an hint towards its solution with
`hint(n)` and the answer with `answer(n)`, where n is the number of the picked question.

In [53]:
%run initialise.py

In [54]:
question(1)

1. Import the numpy package under the name `np` (★☆☆)


In [55]:
import numpy as np

In [56]:
question(2)

2. Print the numpy version and the configuration (★☆☆)


In [57]:
import numpy as np
print(np.version, np.show_config())

{
  "Compilers": {
    "c": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "14.2.1",
      "commands": "cc"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.2.4",
      "commands": "cython"
    },
    "c++": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "14.2.1",
      "commands": "c++"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "linux"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "linux"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.31.188.0",
      "detection method": "pkgconfig",
      "include directory": "/opt/_internal/cpython-3.12.12/lib/python3.12/site-packages/scipy_openblas64/include",
      "lib directory": "/opt/_internal/cpython-3.12.12/lib/python3

/home/zzy39/github/Python/.venv/lib/python3.12/site-packages/numpy/__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


In [58]:
question(3)

3. Create a null vector of size 10 (★☆☆)


In [59]:
import numpy as np
x = np.full(10, 0)
print(x)

[0 0 0 0 0 0 0 0 0 0]


In [60]:
question(4)

4. How to find the memory size of any array (★☆☆)


In [61]:
import numpy as np
x = np.zeros(10)
print(x.size)
print(x.item)
print(x.itemsize)
print(x.itemsize * x.size)

10
<built-in method item of numpy.ndarray object at 0x7d75e876b510>
8
80


In [62]:
question(5)

5. How to get the documentation of the numpy add function from the command line? (★☆☆)


In [63]:
question(6)

6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)


In [64]:
import numpy as np
y = np.zeros(10)
y[4] = 1
print(y)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [65]:
question(7)

7. Create a vector with values ranging from 10 to 49 (★☆☆)


In [66]:
import numpy as np
x = np.arange(10, 50, 1)
y = np.arange(10,50)
print(x)
print(x,y)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49] [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [67]:
question(8)

8. Reverse a vector (first element becomes last) (★☆☆)


In [68]:
import numpy as np
x = np.arange(1,11)
print(x)
i = 0; j = 9
while i < j:
    tmp = x[i]
    x[i] = x[j]
    x[j] = tmp
    i = i + 1
    j = j - 1
print(x)
y = np.arange(1,11)
print(y)
y_reversed = y[::-1]
print(y_reversed)

[ 1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1]
[ 1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1]


In [69]:
question(9)

9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)


In [70]:
import numpy as np
m = np.ones((3,3),dtype=int)
z= 0
for i in range (3):
    for j in range (3):
        m[i][j] = z
        z = z + 1

print(m)

m = np.arange(9).reshape((3,3))
print(m)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [71]:
question(10)

10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)


In [72]:
import numpy as np
arr = np.array([1,2,0,0,4,0])
print(arr)
non_zeros = np.nonzero(arr)
print(non_zeros)

[1 2 0 0 4 0]
(array([0, 1, 4]),)


In [73]:
question(11)

11. Create a 3x3 identity matrix (★☆☆)


In [78]:
import numpy as np
matrix = np.ones(9, dtype=int).reshape((3,3))
print(matrix)
m = np.identity(3, dtype = int)
print(m)
np.fill_diagonal(m, 10)
print(m)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[10  0  0]
 [ 0 10  0]
 [ 0  0 10]]


In [79]:
question(12)

12. Create a 3x3x3 array with random values (★☆☆)


In [89]:
import numpy as np
m = np.random.random((3,3,3))
print(m)
m = np.random.rand(3,3,3)
print(m)
m = np.random.randint(1,101,size=(3,3,3))
print(m)

[[[0.29349773 0.73283503 0.36347055]
  [0.72115278 0.47628274 0.7055862 ]
  [0.8048368  0.71075436 0.79697837]]

 [[0.42329443 0.83770619 0.25267186]
  [0.54286016 0.22557562 0.39821659]
  [0.14184337 0.11179349 0.23267327]]

 [[0.6500226  0.66036328 0.72773448]
  [0.71210973 0.32820565 0.48154542]
  [0.76467491 0.33292486 0.20004258]]]
[[[0.91399775 0.663191   0.31024716]
  [0.6285819  0.7410581  0.49400584]
  [0.18036022 0.88081479 0.27116434]]

 [[0.09407837 0.80167932 0.41176733]
  [0.93719081 0.38280289 0.24459462]
  [0.22339743 0.20312671 0.54437332]]

 [[0.13745861 0.13698351 0.28440528]
  [0.00124288 0.21163519 0.1567484 ]
  [0.84719021 0.09090271 0.82602513]]]
[[[100  86   5]
  [ 87  61   5]
  [ 24  78  92]]

 [[ 32   6  62]
  [ 38  69  25]
  [ 49  30  77]]

 [[ 37  15  90]
  [ 90  81  68]
  [ 41  28  62]]]
